const translations = {
  ko: {changeLanguage:'언어',eyebrow:'GWANGALLI BEACH · BUSAN',heroTitle:'바다를 즐기는<br /><em>가장 깨끗한</em> 방법',heroCopy:'광안리 해수욕장에서 가까운 공중화장실을 찾고, 올바른 분리배출 방법을 확인하세요.',start:'안내 시작하기 <span>↓</span>',stepOne:'STEP 01 · NEARBY GUIDE',toiletTitle:'가까운 공중화장실<br />찾기',toiletCopy:'위치 접근을 허용하면 현재 위치에서 가장 가까운 공중화장실을 안내합니다.',locationReady:'현재 위치를 확인할까요?',locationHint:'위치 정보는 이 기기에서만 사용됩니다.',allowLocation:'위치 허용하기',mapNote:'길찾기 버튼을 누른 뒤 네이버 지도에 출발지와 안내받은 목적지를 입력해 주세요.',stepTwo:'STEP 02 · SORT SMART',recycleTitle:'사진으로 묻고,<br /><em>제대로 버리기</em>',recycleCopy:'분리배출이 헷갈릴 때 사진을 AI에 보여주세요. 재질과 오염 여부에 따른 처리법을 쉽게 확인할 수 있어요.',promptLabel:'AI에 이렇게 물어보세요',copy:'프롬프트 복사',s1t:'비우기',s1d:'내용물은 비워요',s2t:'헹구기',s2d:'이물질을 씻어요',s3t:'분리하기',s3d:'재질별로 나눠요',s4t:'배출하기',s4d:'정해진 곳에 버려요',uploadTitle:'쓰레기 사진 올리기',uploadHint:'사진을 선택해 AI 분석에 사용하세요',stepThree:'STEP 03 · KEEP IT BLUE',issueTitle:'잠깐의 방치가<br />모두의 바다를 바꿉니다',issueTag:'LOCAL ISSUE',issueHeadline:'해변 쓰레기 문제,<br />함께 줄여요.',issueCopy:'해변에 남겨진 쓰레기는 바다로 흘러가 생태계에 오래 남습니다. 가져온 쓰레기는 다시 가져가거나 알맞게 분리배출해 주세요.',readArticle:'관련 기사 보기 ↗',footer:'작은 실천으로 더 깨끗한 광안리를 만듭니다.',nearest:'가장 가까운 공중화장실',directions:'네이버 지도에서 길찾기',copied:'프롬프트를 복사했어요!',locationError:'위치를 가져오지 못했어요. 아래 장소 중 가까운 곳을 골라 주세요.',locations:'가까운 장소 보기'},
  en: {changeLanguage:'Language',eyebrow:'GWANGALLI BEACH · BUSAN',heroTitle:'The <em>cleanest</em> way<br />to enjoy the sea',heroCopy:'Find a nearby public restroom and learn how to sort your waste correctly at Gwangalli Beach.',start:'Start guide <span>↓</span>',stepOne:'STEP 01 · NEARBY GUIDE',toiletTitle:'Find a nearby<br />public restroom',toiletCopy:'Allow location access to find the nearest public restroom from where you are.',locationReady:'Check your current location?',locationHint:'Your location is used only on this device.',allowLocation:'Allow location',mapNote:'After tapping directions, enter your start point and the suggested destination in Naver Map.',stepTwo:'STEP 02 · SORT SMART',recycleTitle:'Ask with a photo,<br /><em>dispose correctly</em>',recycleCopy:'When recycling is confusing, show your photo to AI. It can help you check the material and how to dispose of it.',promptLabel:'Ask AI this',copy:'Copy prompt',s1t:'Empty',s1d:'Empty the contents',s2t:'Rinse',s2d:'Wash off residue',s3t:'Separate',s3d:'Sort by material',s4t:'Dispose',s4d:'Use the right bin',uploadTitle:'Upload a waste photo',uploadHint:'Choose a photo for AI analysis',stepThree:'STEP 03 · KEEP IT BLUE',issueTitle:'A moment of neglect<br />changes everyone’s sea',issueTag:'LOCAL ISSUE',issueHeadline:'Beach waste is a problem<br />we can reduce together.',issueCopy:'Waste left on the beach can flow into the ocean and remain in the ecosystem. Take it with you or sort it properly.',readArticle:'Read related article ↗',footer:'Small actions create a cleaner Gwangalli.',nearest:'Nearest public restroom',directions:'Get directions in Naver Map',copied:'Prompt copied!',locationError:'We could not get your location. Choose the closest place below.',locations:'Show nearby places'},
  ja: {changeLanguage:'言語',eyebrow:'GWANGALLI BEACH · BUSAN',heroTitle:'海を楽しむための<br /><em>いちばんきれいな</em>方法',heroCopy:'広安里海水浴場で近くの公衆トイレを探し、正しい分別方法を確認しましょう。',start:'ガイドを始める <span>↓</span>',stepOne:'STEP 01 · NEARBY GUIDE',toiletTitle:'近くの公衆トイレを<br />探す',toiletCopy:'位置情報を許可すると、現在地から最も近い公衆トイレをご案内します。',locationReady:'現在地を確認しますか？',locationHint:'位置情報はこの端末でのみ使用します。',allowLocation:'位置情報を許可',mapNote:'経路検索を押した後、NAVER地図に出発地と案内された目的地を入力してください。',stepTwo:'STEP 02 · SORT SMART',recycleTitle:'写真で聞いて、<br /><em>正しく捨てる</em>',recycleCopy:'分別に迷ったら、写真をAIに見せてください。材質や汚れに応じた処理方法を確認できます。',promptLabel:'AIへの質問例',copy:'プロンプトをコピー',s1t:'中身を空に',s1d:'中身を出します',s2t:'すすぐ',s2d:'汚れを落とします',s3t:'分ける',s3d:'材質ごとに分けます',s4t:'捨てる',s4d:'決められた場所へ',uploadTitle:'ごみの写真をアップロード',uploadHint:'AI分析用の写真を選択',stepThree:'STEP 03 · KEEP IT BLUE',issueTitle:'少しの放置が<br />みんなの海を変えます',issueTag:'LOCAL ISSUE',issueHeadline:'海辺のごみ問題を<br />一緒に減らしましょう。',issueCopy:'海辺に残されたごみは海へ流れ、生態系に長く残ります。持ち帰るか、正しく分別してください。',readArticle:'関連記事を見る ↗',footer:'小さな行動で、よりきれいな広安里へ。',nearest:'最も近い公衆トイレ',directions:'NAVER地図で経路検索',copied:'プロンプトをコピーしました！',locationError:'位置情報を取得できませんでした。下から近い場所を選んでください。',locations:'近くの場所を見る'},
  zh: {changeLanguage:'语言',eyebrow:'GWANGALLI BEACH · BUSAN',heroTitle:'享受大海的<br /><em>最洁净</em>方式',heroCopy:'在广安里海水浴场寻找附近的公共卫生间，并学习正确的垃圾分类方法。',start:'开始指南 <span>↓</span>',stepOne:'STEP 01 · NEARBY GUIDE',toiletTitle:'寻找附近的<br />公共卫生间',toiletCopy:'允许访问位置后，我们将为您指引距离当前位置最近的公共卫生间。',locationReady:'要确认当前位置吗？',locationHint:'位置信息只会在此设备上使用。',allowLocation:'允许位置访问',mapNote:'点击路线指引后，请在 NAVER 地图中输入出发地和推荐目的地。',stepTwo:'STEP 02 · SORT SMART',recycleTitle:'用照片提问，<br /><em>正确投放</em>',recycleCopy:'不确定如何分类时，请将照片展示给 AI。它可以帮助您确认材质和处理方法。',promptLabel:'这样询问 AI',copy:'复制提示词',s1t:'倒空',s1d:'倒掉内容物',s2t:'冲洗',s2d:'洗去残留物',s3t:'分类',s3d:'按材质分开',s4t:'投放',s4d:'放入正确的箱子',uploadTitle:'上传垃圾照片',uploadHint:'选择用于 AI 分析的照片',stepThree:'STEP 03 · KEEP IT BLUE',issueTitle:'片刻的搁置<br />会改变所有人的大海',issueTag:'LOCAL ISSUE',issueHeadline:'海滩垃圾问题，<br />让我们一起减少。',issueCopy:'留在海滩上的垃圾会流入海洋，并在生态系统中存留很久。请带走垃圾或正确分类投放。',readArticle:'查看相关文章 ↗',footer:'小小的行动，让广安里更洁净。',nearest:'最近的公共卫生间',directions:'在 NAVER 地图中导航',copied:'提示词已复制！',locationError:'无法获取您的位置。请从下方选择最近的地点。',locations:'查看附近地点'}
};
const toilets=[
  {name:'광안해변로 138',lat:35.1538,lng:129.1184}, {name:'광안해변로 219',lat:35.1511,lng:129.1213}, {name:'광안해변로 54번길 222',lat:35.1561,lng:129.1145}, {name:'민락동 181-78',lat:35.1540,lng:129.1258}
];
let lang=localStorage.getItem('ocean-language')||'';
const $=s=>document.querySelector(s);
function applyLanguage(next){lang=next;localStorage.setItem('ocean-language',lang);document.documentElement.lang=lang;const t=translations[lang];document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t[el.dataset.i18n]||'');$('#language-modal').close()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function distance(a,b,c,d){const r=Math.PI/180,x=(c-a)*r,y=(d-b)*r;return 6371*Math.sqrt(x*x+Math.cos(a*r)*Math.cos(c*r)*y*y)}
function showResults(lat,lng){const t=translations[lang];const ordered=[...toilets].sort((a,b)=>distance(lat,lng,a.lat,a.lng)-distance(lat,lng,b.lat,b.lng));const nearest=ordered[0];const list=ordered.map(x=>`<button class="map-choice" data-address="${x.name}">${x.name}</button>`).join('');$('#toilet-result').innerHTML=`<div><p>${t.nearest}</p><strong>${nearest.name}</strong><p>${Math.round(distance(lat,lng,nearest.lat,nearest.lng)*1000)}m</p></div><div class="result-actions"><button class="primary-button map-open" data-address="${nearest.name}">${t.directions}</button><button class="text-button" id="other-locations">${t.locations}</button></div><div class="alternative-list hidden" id="alternative-list">${list}</div>`;$('#toilet-result').classList.remove('hidden');document.querySelectorAll('.map-open,.map-choice').forEach(btn=>btn.addEventListener('click',()=>openMap(btn.dataset.address)));$('#other-locations')?.addEventListener('click',()=>$('#alternative-list').classList.toggle('hidden'))}
function openMap(address){navigator.clipboard?.writeText(address);window.open('https://map.naver.com/','_blank','noopener');toast(`${address} · ${translations[lang].mapNote}`)}
$('#find-location').addEventListener('click',()=>{if(!navigator.geolocation){showResults(35.1538,129.1184);return}navigator.geolocation.getCurrentPosition(p=>showResults(p.coords.latitude,p.coords.longitude),()=>{showResults(35.1538,129.1184);toast(translations[lang].locationError)},{enableHighAccuracy:true,timeout:10000})});
$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt-text').textContent);toast(translations[lang].copied)}catch{toast($('#prompt-text').textContent)}});
$('#photo-input').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const img=$('#preview');img.src=URL.createObjectURL(f);img.style.display='block'});
$('#change-language').addEventListener('click',()=>$('#language-modal').showModal());document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyLanguage(b.dataset.lang)));if(lang)applyLanguage(lang);else $('#language-modal').showModal();
